[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["crates/.agents"]

[profile.dev.package."*"]
opt-level = 2

[workspace.dependencies]
gpui-pre = "0.3.6"
gpui-router = { version = "0.5.0", default-features = false, features = ["gpui-pre", "font-kit", "wayland", "x11"] }
serde = {version = "1.0.229", features = ["derive"]}
tokio = { version = "1.53.1", features = ["full"] }
smol = "2"
anyhow = "1.0.104"

assets = { path = "crates/assets" }
ui = { path = "crates/ui" }
services = { path = "crates/services" }
